#ifndef _DRAGON_H
#define _DRAGON_H

#include <stdint.h>
#include "esp_log.h"
#include "esp_mac.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include "cJSON.h"
#define SETTINGS_FILE "/data/settings.json"
#define DEFAULT_FILE  "/data/default.json"

#define NAME_BUF_SIZE       32
#define BADGE_BUF_SIZE      64
#define BADGE_NAME_MAX_SIZE 28
#define BADGE_URL_SIZE      256
#define NAME_MAX_SIZE       64
#define SCHEDULE_BUFFER_LEN 10000

#define MAX_NEARBY_NODE 16
#define SIZEOF(a)       sizeof(a) / sizeof(*a)

enum badge_item_id {
  WEB_LOGIN_ID,
  WIFI_SSID_ID,
  WIFI_PASSSWORD_ID,
  DEVICE_NAME_ID,
  SYNC_PATH_ID,
  PERSON_NAME_ID,
  PERSON_ORGANIZATION_ID,
  PERSON_JOB_ID,
  PERSON_MESSAGE_ID,
  PERSON_URL_ID,
  SECRET_NAME_ID,
  SECRET_ORGANIZATION_ID,
  SECRET_JOB_ID,
  SECRET_MESSAGE_ID,
  SECRET_URL_ID
};
// These variables are autogenerated and compiled
extern const char *GIT_TAG;
extern const char *GIT_REV;
extern const char *GIT_BRANCH;

typedef struct
{
  char name[NAME_MAX_SIZE];
  char organization[NAME_MAX_SIZE];
  char job[NAME_MAX_SIZE];
  char message[NAME_MAX_SIZE];
  char url[BADGE_URL_SIZE];
} person_t;

typedef struct {
  uint8_t mac[6];
  uint16_t short_mac;
  uint8_t device_id;
  char device_name[NAME_BUF_SIZE];

  char web_login[BADGE_BUF_SIZE];
  char ap_ssid[NAME_BUF_SIZE];
  char ap_password[NAME_BUF_SIZE];
  char sta_ssid[NAME_BUF_SIZE];
  char sta_password[NAME_BUF_SIZE];
  char sync_path[BADGE_BUF_SIZE];

  person_t person;
  person_t secret;

  // Display brightness settings
  uint8_t brightness_max;
  uint8_t brightness_mid;
  uint8_t brightness_off;

  char *schedule_buffer;
  bool (*update)(enum badge_item_id id, char *data);
  // bool (*update_schedule)();
} badge_obj_t;

extern badge_obj_t badge_obj;

void badge_init();
char *load_file_content(const char *filename);

#endif  // _DRAGON_H
